### ISSUE TITLE
How to register credentials for premium video download?

### ISSUE THREAD

**Issue by sanjibukai** [qiandongyq/coursehunters-video-downloader#5]
Hello,

I'm unable to download any Premium course while I have an active subscription.
I mean where should I enter my credentials?

In the demo you provided as a gif, you are downloading the react hooks course which is a premium course.

Where did you register your credentials?

Thank you.

**Comment by qiandongyq** [comment]
It is not implemented, If you have a Premium account, you can just download the video on the courshunters website itself. This app was initially created to help people to download free videos.
If you want to download premium videos, please check this
https://github.com/alekseylovchikov/ch-download

Thanks
